from django.conf.urls import url
from backend.views import *

# backend url 配置
urlpatterns = [
    url(r'^info$',info,name='info'),
    url(r'^logout$',logout,name='logout'),
    url(r'^getTcTreatHistroryData/',getTcTreatHistroryData,name='getTcTreatHistroryData'),
    url(r'^getOrderSelectData/',getOrderSelectData,name='getOrderSelectData'),
    url(r'^treat_histrorys/',treat_histrorys,name='treat_histrorys'),
    url(r'^treat_subhistorys/',treat_subhistorys,name='treat_subhistorys'),
    # url(r'^txDeviceBymonth/',countTxDeviceBymonth,name='txDeviceBymonth'),
    # url(r'^operateByYear/',operateByYear,name='operateByYear'),
    # url(r'^analyseBykind/',analyseBykind,name='analyseBykind'),
    # url(r'^analyseFirstTx/',analyseFirstTx,name='analyseFirstTx'),
    # url(r'^analysePTH/',analysePTH,name='analysePTH'),
    # url(r'^analyseCaP/',analyseCaP,name='analyseCaP'),
    # url(r'^AlarmLab/',AlarmLab,name='AlarmLab'),
    # url(r'^analyseBfzBymonth/',analyseBfzBymonth,name='analyseBfzBymonth'),
    # url(r'^analyseBloodPressure/',analyseBloodPressure,name='analyseBloodPressure'),
    # url(r'^analyseByYuanfa/',analyseByYuanfa,name='analyseByYuanfa'),
    # url(r'^analyseZhuangui/',analyseZhuangui,name='analyseZhuangui'),
    # url(r'^analyseZhengzhuang/',analyseZhengzhuang,name='analyseZhengzhuang'),
    # url(r'^analyseDrugByyear/',analyseDrugByyear,name='analyseDrugByyear'),
    # url(r'^analyseMaterialByyear/',analyseMaterialByyear,name='analyseMaterialByyear'),
    # url(r'^analysedrug/',analysedrug,name='analysedrug'),
    # url(r'^analysedrugDetail/',analysedrugDetail,name='analysedrugDetail'),
    # url(r'^analysematerial/',analysematerial,name='analysematerial'),
    # url(r'^analysematerialDetail/',analysematerialDetail,name='analysematerialDetail'),
    # url(r'^analyseDrugstock/',analyseDrugstock,name='analyseDrugstock'),
    # url(r'^analyseMaterialstock/',analyseMaterialstock,name='analyseMaterialstock'),
    # url(r'^analyseDeptCharge/',analyseDeptCharge,name='analyseDeptCharge'),
    # url(r'^deptChargeBymonth/',DeptChargeBymonth,name='deptChargeBymonth'),
    # url(r'^getLabreason/',getLabreason,name='getLabreason'),
    # url(r'^getLabItems/',getLabItems,name='getLabItems'),
    # url(r'^analyseLabResultData/',analyseLabResultData,name='analyseLabResultData'),
    # url(r'^getPatient_yz/',getPatient_yz,name='getPatient_yz'),
    # url(r'^getTimeIntersect/',getTimeIntersect,name='getTimeIntersect'),
    # url(r'^getXgtonglu/',getXgtonglu,name='getXgtonglu'),
    # url(r'^getXgtongluType/',getXgtongluType,name='getXgtongluType'),
    # url(r'^getMaterialType/',getMaterialType,name='getMaterialType'),
    # url(r'^PatientsToRegister/',PatientsToRegister,name='PatientsToRegister'),
    # url(r'^copyTotouxi_drug/',copyTotouxi_drug,name='copyTotouxi_drug'),
    # url(r'^getNurses/',getNurses,name='getNurses'),
    # url(r'^getProPostRecord/',getProPostRecord,name='getProPostRecord'),
    # url(r'^getExpenseRecord/',getExpenseRecord,name='getExpenseRecord'),
    # url(r'^getDrugAlert/',getDrugAlert,name='getDrugAlert'),
    # url(r'^getLab_Test_Items/',getLab_Test_Items,name='getLab_Test_Items'),
    # url(r'^getExam_Items/',getExam_Items,name='getExam_Items'),
    url(r'^getOrganization/',getOrganization,name='getOrganization'),
    url(r'^getAllSelectData/',getAllSelectData,name='getAllSelectData'),
    # url(r'^down_file/', down_file,name='down_file'),
]