# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-08 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_groupmenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChildMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isvisible', models.BooleanField(default=1)),
                ('path', models.CharField(blank=True, max_length=160)),
                ('name', models.CharField(blank=True, default='', max_length=160)),
                ('title', models.CharField(default='', max_length=160)),
                ('icon', models.CharField(default='', max_length=160)),
                ('component', models.CharField(default='', max_length=260)),
                ('child_menu_id', models.IntegerField(default=1, verbose_name='childid')),
                ('groupmenu', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.GroupMenu', verbose_name='角色菜单')),
            ],
        ),
    ]
