# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-08 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_childmenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='sysRight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='权限名称')),
                ('description', models.CharField(max_length=300, verbose_name='权限描述')),
                ('modName', models.CharField(max_length=100, verbose_name='模块名称')),
                ('type', models.IntegerField(default=0, verbose_name='权限类别')),
            ],
        ),
    ]
