# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-08 15:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0006_groupright'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrmCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='名称')),
                ('description', models.CharField(max_length=2000, verbose_name='简称')),
                ('web', models.CharField(max_length=500, verbose_name='公司网址')),
            ],
        ),
        migrations.CreateModel(
            name='HrmDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='名称')),
                ('description', models.CharField(max_length=1000, verbose_name='标识')),
                ('subcompanyid', models.IntegerField(null=True, verbose_name='所属分部id')),
                ('supdepid', models.IntegerField(null=True, verbose_name='所属部门id')),
                ('allsupdepid', models.CharField(max_length=2000, null=True, verbose_name='所有上级部门id')),
                ('showorder', models.IntegerField(default=0, verbose_name='序号')),
                ('canceled', models.IntegerField(default=0, verbose_name='封存标志')),
                ('code', models.CharField(max_length=500, verbose_name='分部编号')),
                ('bmfzr', models.CharField(max_length=1000, null=True, verbose_name='负责人')),
                ('bmfgld', models.CharField(max_length=1000, null=True, verbose_name='分管领导')),
                ('tlevel', models.IntegerField(default=0, verbose_name='等级')),
            ],
        ),
        migrations.CreateModel(
            name='HrmSubCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='名称')),
                ('description', models.CharField(max_length=2000, verbose_name='简称')),
                ('companyid', models.IntegerField(null=True, verbose_name='公司总部id')),
                ('supsubcomid', models.IntegerField(null=True, verbose_name='上级分部id')),
                ('url', models.CharField(max_length=1000, verbose_name='url')),
                ('showorder', models.IntegerField(default=0, verbose_name='序号')),
                ('canceled', models.IntegerField(default=0, verbose_name='封存标志')),
                ('code', models.CharField(max_length=500, verbose_name='分部编号')),
                ('tlevel', models.IntegerField(default=0, verbose_name='等级')),
            ],
        ),
        migrations.CreateModel(
            name='subCompanyField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='字段名称')),
                ('display', models.CharField(max_length=200, verbose_name='中文名称')),
                ('show', models.BooleanField(default=0, verbose_name='是否显示')),
                ('width', models.IntegerField(default=60, verbose_name='宽度')),
            ],
        ),
        migrations.CreateModel(
            name='UserDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depCenter', to='backend.HrmDepartment', verbose_name='中心')),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='员工')),
            ],
        ),
    ]
