# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-08 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_hrmcompany_hrmdepartment_hrmsubcompany_subcompanyfield_userdepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.IntegerField(default=1, verbose_name='test')),
            ],
            options={
                'permissions': (('organization', '组织机构设置'), ('xlog', '操作日志')),
            },
        ),
    ]
