# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-08 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='coo_hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('begindate', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('enddate', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='地址')),
                ('comment', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('contactman', models.CharField(blank=True, max_length=60, null=True, verbose_name='联系人')),
                ('telphone', models.CharField(blank=True, max_length=60, null=True, verbose_name='电话')),
            ],
        ),
    ]
