# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-09 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20190909_0725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'permissions': (('coo_hospital', '合作医院'), ('dept_dict', '科室字典'), ('organization', '组织机构设置'), ('xlog', '操作日志'))},
        ),
    ]
