# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-10 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20190910_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='dept_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptdict_id', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.dept_dict', verbose_name='科室')),
                ('postdict_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.post_dict', verbose_name='岗位')),
            ],
        ),
    ]
