# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-10 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_dept_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dept_post',
            old_name='deptdict_id',
            new_name='deptdict',
        ),
        migrations.RenameField(
            model_name='dept_post',
            old_name='postdict_id',
            new_name='postdict',
        ),
    ]
