# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-10 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20190910_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_dict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectid', models.IntegerField(default=1, verbose_name='项目id')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('isindependent', models.BooleanField(default=True, verbose_name='能否独立开单')),
                ('type', models.SmallIntegerField(default=0, verbose_name='是否为套餐')),
                ('amount', models.IntegerField(default=0, verbose_name='数量')),
                ('comment', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.project_dict')),
            ],
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'permissions': (('project_dict', '项目字典'), ('finance_month', '财务月'), ('coo_hospital', '合作医院'), ('dept_dict', '科室字典'), ('post_dict', '岗位字典'), ('dept', '中心科室'), ('organization', '组织机构设置'), ('xlog', '操作日志'))},
        ),
    ]
