# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-11 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_auto_20190911_0655'),
    ]

    operations = [
        migrations.CreateModel(
            name='tuitionFee_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0, verbose_name='数值')),
                ('comment', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.project_dict', verbose_name='项目id')),
                ('tuition', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.tuition_dict', verbose_name='带教费类型id')),
                ('tuitionfee', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.tuitionFee', verbose_name='带教费id')),
            ],
        ),
    ]
