# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-11 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_auto_20190911_0708'),
    ]

    operations = [
        migrations.CreateModel(
            name='benefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='benefit_dict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('comment', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
            ],
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'permissions': (('tuitionFee', '带教费'), ('performance_dict', '绩效字典'), ('benefit_dict', '工资福利字典'), ('performance', '中心绩效'), ('benefit', '中心工资福利字典'), ('tuition_dict', '带教费类型'), ('project_dict', '项目字典'), ('finance_month', '财务月'), ('coo_hospital', '合作医院'), ('dept_dict', '科室字典'), ('post_dict', '岗位字典'), ('dept', '中心科室'), ('organization', '组织机构设置'), ('xlog', '操作日志'))},
        ),
        migrations.AddField(
            model_name='benefit',
            name='benefitdict',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.benefit_dict', verbose_name='绩效id'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='hrmdepartment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.HrmDepartment', verbose_name='中心id'),
        ),
    ]
