# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-11 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_auto_20190911_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_dict',
            name='projectid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='项目id'),
        ),
    ]
