# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-11 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_auto_20190911_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_dict',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.project_dict', to_field='projectid'),
        ),
    ]
