# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-11 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_auto_20190911_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_dict',
            name='isindependent',
            field=models.SmallIntegerField(default=1, verbose_name='能否独立开单'),
        ),
    ]
