# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-11 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_auto_20190911_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_dict',
            name='isindependent',
            field=models.BooleanField(default=1, verbose_name='能否独立开单'),
        ),
        migrations.AlterField(
            model_name='project_dict',
            name='type',
            field=models.BooleanField(default=0, verbose_name='是否为套餐'),
        ),
    ]
