# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-11 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_auto_20190911_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, verbose_name='项目id')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('isindependent', models.BooleanField(default=1, verbose_name='能否独立开单')),
                ('type', models.BooleanField(default=0, verbose_name='是否为套餐')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='数量')),
                ('comment', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('hrmdepartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.HrmDepartment', verbose_name='中心')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.project')),
            ],
        ),
    ]
