# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-11 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='价格'),
        ),
    ]
