# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-11 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_project_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'permissions': (('tuitionFee', '带教费'), ('performance_dict', '绩效字典'), ('benefit_dict', '工资福利字典'), ('performance', '中心绩效'), ('benefit', '中心工资福利字典'), ('tuition_dict', '带教费类型'), ('project_dict', '项目字典'), ('project', '中心项目'), ('finance_month', '财务月'), ('coo_hospital', '合作医院'), ('dept_dict', '科室字典'), ('post_dict', '岗位字典'), ('dept', '中心科室'), ('organization', '组织机构设置'), ('xlog', '操作日志'))},
        ),
    ]
