# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-13 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_auto_20190913_0558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='huiyuan_set',
            name='deptdict',
        ),
        migrations.AddField(
            model_name='huiyuan_set',
            name='projectdict',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.project_dict', verbose_name='科室id'),
        ),
    ]
