# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-13 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0043_auto_20190913_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='家庭住址'),
        ),
    ]
