# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-13 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0044_client_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuitionfee',
            name='deptdict',
        ),
        migrations.AddField(
            model_name='tuitionfee',
            name='dept',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.dept', verbose_name='科室id'),
        ),
    ]
