# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-14 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0046_auto_20190913_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='client_from',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('comment', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='client_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('comment', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='jinjizheng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('comment', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
            ],
        ),
    ]
