# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-14 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0048_auto_20190914_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_register',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.dept', verbose_name='登记科室id'),
        ),
    ]
