# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-14 16:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0049_auto_20190914_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='client_jinjizheng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adddate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加日期')),
                ('adduser', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='添加人id')),
                ('client', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.client', verbose_name='客户id')),
                ('jinjizheng', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.jinjizheng', verbose_name='禁忌症id')),
            ],
        ),
        migrations.CreateModel(
            name='client_jinjizheng_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(blank=True, null=True, verbose_name='操作类型')),
                ('adddate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加日期')),
                ('adduser', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='添加人id')),
                ('client_register', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.client_register', verbose_name='客户id')),
                ('jinjizheng', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.jinjizheng', verbose_name='禁忌症id')),
            ],
        ),
    ]
