# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-14 20:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0050_client_jinjizheng_client_jinjizheng_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketdate', models.DateTimeField(blank=True, null=True, verbose_name='宣教日期')),
                ('orderdate', models.DateTimeField(blank=True, null=True, verbose_name='开单日期')),
                ('times', models.IntegerField(default=0, verbose_name='开单次数')),
                ('issuccess', models.SmallIntegerField(default=0, verbose_name='宣教是否成功')),
                ('issell', models.SmallIntegerField(default=0, verbose_name='是否需宣教')),
                ('residue', models.IntegerField(default=0, verbose_name='剩余次数')),
                ('receivable', models.FloatField(default=0, verbose_name='应收金额')),
                ('discount', models.FloatField(default=0, verbose_name='优惠金额')),
                ('receipts', models.FloatField(default=0, verbose_name='实收金额')),
                ('isproorder', models.SmallIntegerField(default=0, verbose_name='是否预开单')),
                ('isacquire', models.SmallIntegerField(default=0, verbose_name='是否收单')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('type', models.SmallIntegerField(default=0, verbose_name='是否套餐')),
                ('price', models.FloatField(default=0, verbose_name='价格')),
                ('comment', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('iszengpin', models.SmallIntegerField(default=0, verbose_name='是否赠品')),
                ('adduser', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='add_user', to=settings.AUTH_USER_MODEL, verbose_name='开单人id')),
                ('client', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.client', verbose_name='客户id')),
                ('hrmdepartment', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.HrmDepartment', verbose_name='中心id')),
                ('marketdept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_dept', to='backend.dept', verbose_name='宣教科室id')),
                ('marketman', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='market_man', to=settings.AUTH_USER_MODEL, verbose_name='宣教人id')),
                ('marketpost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_post', to='backend.post_dict', verbose_name='宣教岗位id')),
                ('orderdept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_dept', to='backend.dept', verbose_name='开单科室id')),
                ('orderpost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_post', to='backend.post_dict', verbose_name='开单岗位id')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.order')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.project', verbose_name='开单项目id')),
            ],
        ),
    ]
