# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-15 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0052_treat'),
    ]

    operations = [
        migrations.CreateModel(
            name='dept_client_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clienttype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.client_type', verbose_name='客户类型')),
                ('deptdict', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.dept_dict', verbose_name='科室')),
            ],
        ),
    ]
