# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-15 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0053_dept_client_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_register',
            name='diagnose',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='诊断'),
        ),
    ]
