# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-15 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0055_auto_20190915_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_register',
            name='BMI',
            field=models.FloatField(blank=True, null=True, verbose_name='当前BMI'),
        ),
        migrations.AlterField(
            model_name='client_register',
            name='burutype',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='哺乳方式'),
        ),
        migrations.AlterField(
            model_name='client_register',
            name='chanci',
            field=models.IntegerField(blank=True, null=True, verbose_name='产次'),
        ),
        migrations.AlterField(
            model_name='client_register',
            name='chanhouzhouqi',
            field=models.IntegerField(blank=True, null=True, verbose_name='产后周期'),
        ),
        migrations.AlterField(
            model_name='client_register',
            name='client_type',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='客户类型'),
        ),
        migrations.AlterField(
            model_name='client_register',
            name='fenmiantype',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='分娩方式'),
        ),
        migrations.AlterField(
            model_name='client_register',
            name='frequency',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='运动频率'),
        ),
        migrations.AlterField(
            model_name='client_register',
            name='ganyutype',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='干预方式'),
        ),
        migrations.AlterField(
            model_name='client_register',
            name='healthtype',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='健康类型'),
        ),
        migrations.AlterField(
            model_name='client_register',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='身高cm'),
        ),
        migrations.AlterField(
            model_name='client_register',
            name='preBMI',
            field=models.FloatField(blank=True, null=True, verbose_name='孕前BMI'),
        ),
        migrations.AlterField(
            model_name='client_register',
            name='preweight',
            field=models.FloatField(blank=True, null=True, verbose_name='孕前体重kg'),
        ),
        migrations.AlterField(
            model_name='client_register',
            name='shoushuype',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='手术方式'),
        ),
        migrations.AlterField(
            model_name='client_register',
            name='sourcedept',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='来源科室id'),
        ),
        migrations.AlterField(
            model_name='client_register',
            name='sportttime',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='运动时间'),
        ),
        migrations.AlterField(
            model_name='client_register',
            name='sporttype',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='运动类型'),
        ),
        migrations.AlterField(
            model_name='client_register',
            name='taishu',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='胎数'),
        ),
        migrations.AlterField(
            model_name='client_register',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='当前体重kg'),
        ),
        migrations.AlterField(
            model_name='client_register',
            name='workqiangdu',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='工作强度'),
        ),
        migrations.AlterField(
            model_name='client_register',
            name='yunci',
            field=models.IntegerField(blank=True, null=True, verbose_name='孕次'),
        ),
        migrations.AlterField(
            model_name='client_register',
            name='yunzhou',
            field=models.IntegerField(blank=True, null=True, verbose_name='孕周'),
        ),
    ]
