# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-17 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0058_auto_20190917_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='isproorder',
            field=models.SmallIntegerField(default=1, verbose_name='是否预开单'),
        ),
    ]
