# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-19 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0060_order_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='depth',
            field=models.IntegerField(default=0, verbose_name='层次'),
        ),
    ]
