# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-19 08:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0061_project_depth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='depth',
        ),
    ]
