# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-19 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0062_remove_project_depth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='marketdate',
            field=models.DateField(blank=True, null=True, verbose_name='宣教日期'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderdate',
            field=models.DateField(blank=True, null=True, verbose_name='开单日期'),
        ),
    ]
