# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-19 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0063_auto_20190919_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='adduser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='add_user', to='backend.userProfile', verbose_name='开单人id'),
        ),
        migrations.AlterField(
            model_name='order',
            name='marketman',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='market_man', to='backend.userProfile', verbose_name='宣教人id'),
        ),
    ]
