# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-19 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0064_auto_20190919_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='adduser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='add_user', to='backend.userProfile', verbose_name='开单人id'),
        ),
    ]
