# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-20 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0069_auto_20190920_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treat',
            name='adduser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adduser_treat', to='backend.userProfile', verbose_name='开单人id'),
        ),
    ]
