# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-26 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0070_auto_20190920_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderdate',
        ),
        migrations.AddField(
            model_name='treat',
            name='isproorder',
            field=models.SmallIntegerField(default=0, verbose_name='是否立即治疗'),
        ),
    ]
