# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-26 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0071_auto_20190926_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='isproorder',
            field=models.SmallIntegerField(default=0, verbose_name='是否立即治疗'),
        ),
        migrations.AlterField(
            model_name='treat',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_treat', to='backend.treat'),
        ),
    ]
