# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-28 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0074_order_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_jinjizheng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('jinjizheng', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.jinjizheng', verbose_name='禁忌症id')),
                ('projectdict', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.project_dict', verbose_name='项目id')),
            ],
        ),
    ]
