# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-29 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0075_project_jinjizheng'),
    ]

    operations = [
        migrations.AddField(
            model_name='treat',
            name='diagnosis',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='诊断'),
        ),
        migrations.AddField(
            model_name='treat',
            name='guide',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='膳食指导'),
        ),
        migrations.AddField(
            model_name='treat',
            name='healthtype',
            field=models.SmallIntegerField(blank=True, choices=[('0', '初检'), ('1', '复检')], default='0', null=True, verbose_name='健康类型'),
        ),
        migrations.AddField(
            model_name='treat',
            name='treatpost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treat_post', to='backend.post_dict', verbose_name='治疗岗位id'),
        ),
        migrations.AddField(
            model_name='treat',
            name='treattype',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='检测类型'),
        ),
        migrations.AddField(
            model_name='treat',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='当前体重kg'),
        ),
        migrations.AddField(
            model_name='treat',
            name='yunzhou',
            field=models.IntegerField(blank=True, null=True, verbose_name='孕周'),
        ),
    ]
