# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-29 14:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0077_auto_20190929_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_register',
            name='healthtype',
            field=models.CharField(blank=True, default='', max_length=200, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')], verbose_name='健康类型'),
        ),
    ]
