# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-29 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0081_auto_20190929_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='treat',
            name='register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.client_register', verbose_name='客户登记id'),
        ),
    ]
