# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-30 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0082_treat_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treat',
            name='operatedate',
            field=models.DateField(blank=True, null=True, verbose_name='操作日期'),
        ),
    ]
