# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-10-01 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0085_auto_20191001_0720'),
    ]

    operations = [
        migrations.CreateModel(
            name='callback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.IntegerField(default=0, verbose_name='开单次数')),
                ('residue', models.IntegerField(default=0, verbose_name='剩余次数')),
                ('ishospital', models.SmallIntegerField(default=0, verbose_name='是否回院')),
                ('hospitaldate', models.DateField(blank=True, null=True, verbose_name='回院日期')),
                ('isfinish', models.SmallIntegerField(default=0, verbose_name='是否完成')),
                ('handledate', models.DateField(blank=True, null=True, verbose_name='回访日期')),
                ('begindate', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('enddate', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('ispreorder', models.SmallIntegerField(default=0, verbose_name='是否立即治疗')),
                ('comment', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('client', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.client', verbose_name='客户id')),
                ('dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dept_register', to='backend.dept', verbose_name='登记科室id')),
                ('handleman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handle_user', to='backend.userProfile', verbose_name='回访人id')),
                ('hrmdepartment', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.HrmDepartment', verbose_name='中心id')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.order', verbose_name='订单id')),
            ],
        ),
    ]
