# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-10-02 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0087_auto_20191002_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='callback',
            name='callbacktype',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='回访类型'),
        ),
    ]
