# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-10-02 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0089_callback_isacquire'),
    ]

    operations = [
        migrations.AddField(
            model_name='callback',
            name='execute',
            field=models.SmallIntegerField(default=0, verbose_name='是否立即治疗'),
        ),
        migrations.AddField(
            model_name='callback',
            name='weight',
            field=models.FloatField(default=0, verbose_name='体重'),
        ),
    ]
