# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-10-02 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0091_auto_20191002_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='callback',
            name='healthtype',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='健康类型'),
        ),
    ]
