# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-10-03 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0092_callback_healthtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='callback',
            name='diagnosis',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='诊断'),
        ),
        migrations.AddField(
            model_name='callback',
            name='guide',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='膳食指导'),
        ),
    ]
