# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-10-04 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0093_auto_20191003_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='callback',
            name='treat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.treat', verbose_name='治疗id'),
        ),
        migrations.AddField(
            model_name='treat',
            name='begindate',
            field=models.DateField(blank=True, null=True, verbose_name='预约开始日期'),
        ),
        migrations.AddField(
            model_name='treat',
            name='enddate',
            field=models.DateField(blank=True, null=True, verbose_name='预约结束日期'),
        ),
        migrations.AddField(
            model_name='treat',
            name='isAppoint',
            field=models.SmallIntegerField(default=0, verbose_name='是否预约'),
        ),
    ]
