# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-10-06 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0095_auto_20191004_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='问卷名称')),
                ('adddate', models.DateField(auto_now_add=True, verbose_name='添加日期')),
                ('comment', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('adduser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.userProfile', verbose_name='添加人id')),
            ],
        ),
    ]
