# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-10-07 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0097_auto_20191007_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treat',
            name='yaling',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='是否使用引导哑铃'),
        ),
    ]
