# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-10-07 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0098_auto_20191007_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='callback',
            name='breast',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='乳房情况'),
        ),
        migrations.AddField(
            model_name='callback',
            name='burufs',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='哺乳方式'),
        ),
        migrations.AddField(
            model_name='callback',
            name='elu',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='恶露情况'),
        ),
        migrations.AddField(
            model_name='callback',
            name='huiyin',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='伤口会阴情况'),
        ),
        migrations.AddField(
            model_name='callback',
            name='milk',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='乳汁情况'),
        ),
        migrations.AddField(
            model_name='callback',
            name='rutou',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='乳头情况'),
        ),
        migrations.AddField(
            model_name='callback',
            name='sleep',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='睡眠情况'),
        ),
        migrations.AddField(
            model_name='callback',
            name='yinshi',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='饮食情况'),
        ),
    ]
