# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-10-11 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0099_auto_20191007_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='survey_title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='问卷名称')),
                ('adddate', models.DateField(auto_now_add=True, verbose_name='添加日期')),
                ('comment', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('sn', models.IntegerField(default=0, verbose_name='序列号,每张问卷的所有题目都有唯一序列号')),
                ('adduser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.userProfile', verbose_name='添加人id')),
                ('survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.survey', verbose_name='问卷id')),
            ],
        ),
        migrations.CreateModel(
            name='survey_title_answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=200, null=True, verbose_name='题目回答选项')),
                ('score', models.IntegerField(default=0, verbose_name='每个选项的分数')),
                ('sn', models.IntegerField(default=0, verbose_name='序列号,每张问卷的所有选项都有唯一序列号')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.survey_title', verbose_name='题目id')),
            ],
        ),
    ]
