# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-10-11 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0101_treat_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='treat_survey',
            name='score',
            field=models.FloatField(default=0, verbose_name='分数'),
        ),
        migrations.AddField(
            model_name='treat_survey',
            name='valuedate',
            field=models.DateField(blank=True, null=True, verbose_name='评估(干预)日期'),
        ),
        migrations.AlterField(
            model_name='treat_survey',
            name='adddate',
            field=models.DateField(blank=True, null=True, verbose_name='添加日期'),
        ),
    ]
