# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-10-11 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0102_auto_20191011_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treat_survey',
            name='adddate',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='添加日期'),
        ),
    ]
