# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-10-12 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0105_remove_survey_result_valuedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey_title',
            name='type',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='题目类型'),
        ),
    ]
