# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-10-12 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0106_survey_title_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey_result',
            name='score',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='分数'),
        ),
    ]
